Add version flag, update dependencies
VictoriaMetrics/grafana-datasource pull request #104
Opened 2023-09-28 09:21 UTC by dmitryk-dk

Enable version flag 
<img width="842" alt="Screenshot 2023-09-28 at 11 19 58" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/12189570/8e613a49-3a01-40a6-a28b-76c4b77202d4">

Updated dependencies for the backend plugin

2023-09-28 09:36 UTC, denisgolius reviewed
Only the one question stop me from approving =)

2023-09-28 09:36 UTC, denisgolius commented on go.mod
> +go 1.20
What about go 1.21 ?

2023-09-28 10:37 UTC, dmitryk-dk commented on go.mod
> +go 1.20
updated go version

2023-10-02 12:41 UTC, denisgolius approved these changes
LGTM!

2023-10-10 14:45 UTC, hagen1778 requested changes

2023-10-10 14:45 UTC, hagen1778 commented on pkg/buildinfo/version.go
> +var version = flag.Bool("version", false, "Show VictoriaMetrics version")
This should be updated accordingly

2023-10-10 14:45 UTC, hagen1778 commented on CHANGELOG.md
> +* FEATURE: add a `--version` flag for backend datasource, update backend plugin to a latest release version. See [this issue](https://github.com/VictoriaMetrics/grafana-datasource/issues/68).
```suggestion
* FEATURE: add `--version` flag for backend datasource binary. See [this issue](https://github.com/VictoriaMetrics/grafana-datasource/issues/68).
```

2023-10-11 08:01 UTC, dmitryk-dk commented on pkg/buildinfo/version.go
> +var version = flag.Bool("version", false, "Show VictoriaMetrics version")
updated

2023-10-11 08:01 UTC, dmitryk-dk commented on CHANGELOG.md
> +* FEATURE: add a `--version` flag for backend datasource, update backend plugin to a latest release version. See [this issue](https://github.com/VictoriaMetrics/grafana-datasource/issues/68).
updated

2023-10-12 13:35 UTC, hagen1778 approved these changes

2023-10-12 13:35 UTC, merged